#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # The first game sets the initial records
    min_record = scores[0]
    max_record = scores[0]
    
    min_breaks = 0
    max_breaks = 0
    
    # Start checking from the second game (index 1)
    for i in range(1, len(scores)):
        if scores[i] > max_record:
            # New high record found
            max_record = scores[i]
            max_breaks += 1
        elif scores[i] < min_record:
            # New low record found
            min_record = scores[i]
            min_breaks += 1
            
    return [max_breaks, min_breaks]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
