#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    # Check if the first kangaroo is actually able to catch up
    # It must be behind AND moving faster
    if v1 > v2:
        # Check if the distance between them is divisible by the 
        # difference in their speeds
        if (x2 - x1) % (v1 - v2) == 0:
            return "YES"
        else:
            return "NO"
    else:
        # If v2 >= v1 and x2 > x1, the first kangaroo can never catch up
        return "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    x1 = int(first_multiple_input[0])

    v1 = int(first_multiple_input[1])

    x2 = int(first_multiple_input[2])

    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
