#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'staircase' function below.
#
# The function accepts INTEGER n as parameter.
#

def staircase(n):
   # Iterate from 1 up to n (inclusive)
    for i in range(1, n + 1):
        # Calculate number of spaces and symbols
        spaces = ' ' * (n - i)
        symbols = '#' * i
        
        # Concatenate and print
        print(spaces + symbols)

if __name__ == '__main__':
    n = int(input().strip())

    staircase(n)
