#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Extract AM/PM
    meridiem = s[-2:]
    # Extract the hour, minute, and second parts
    hour = int(s[:2])
    rest_of_time = s[2:-2]
    
    if meridiem == "PM":
        if hour != 12:
            hour += 12
    else: # It is AM
        if hour == 12:
            hour = 0
            
    # Format the hour back to two digits (e.g., 0 becomes '00')
    return f"{hour:02}{rest_of_time}"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
